---

- name: REPLICATION | MASTER | Setup postgres config on master
  include_tasks: postgres_config.yml
  vars:
    postgresql_global_config_options: "{{ postgres_replication_master_conf_lines }}"

- name: REPLICATION | MASTER | Add replcation user
  include_tasks: users.yml
  vars:
    postgresql_users:
      - name: "{{ postgres_replication_user }}"
        password: "{{ postgres_replication_password }}"
        role_attr_flags: replication

- name: REPLICATION | MASTER | Add trust in pg_hba.conf
  lineinfile:
    state: present
    dest: "{{ postgresql_config_path }}/pg_hba.conf"
    regexp: 'host.*replication.*{{ item }}/32.*trust'
    line: 'host    replication    {{ postgres_replication_user }}  {{ item }}/32 trust'
  loop: "{{ postgres_replication_replica_address }}"
  notify: restart postgresql
